<?php

declare(strict_types=1);

namespace Test\Unit;

use App\Router;
use PHPUnit\Framework\TestCase;

class RouterTest extends TestCase
{
    private Router $router;
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->router = new Router();
    }

    /** @test */
    public function itRegisterARoute(): void
    {
        // when we call a register method
        $this->router->register('get', '/users', ['Users', 'index']);

        $expected = [
            'get' => [
                '/users' => ['Users', 'index']
            ]
        ];

        // then we assert route
        $this->assertEquals($expected, $this->router->routes());
    }

    /** @test */
    public function itRegisterAGetRoute(): void
    {
        $this->router->get('/users', ['Users', 'index']);

        $expected = [
            'get' => [
                '/users' => ['Users', 'index']
            ]
        ];


        $this->assertEquals($expected, $this->router->routes());
    }

    /** @test */
    public function itRegisterAPostRoute(): void
    {
        $this->router->post('/users', ['Users', 'store']);

        $expected = [
            'post' => [
                '/users' => ['Users', 'store']
            ]
        ];


        $this->assertEquals($expected, $this->router->routes());
    }

    /** @test */
    public function thereAreNoRoutesWhenRouterIsCreated(): void
    {
        $router = new Router(); // new instation of Router because of test spec

        $this->assertEmpty($router->routes());
    }
}